# Outline
- Creating a 2D NumPy Array
- Seeing the "shape" of NumPy Array
- Subsetting 2 2D NumPy Array

## Creating a 2D NumPy Array 

In [1]:
import numpy as np

In [ ]:
# List of masses
mass = [12,20,32]

In [3]:
#List of volumes
volume = [36,18,10]

In [9]:
#Create a list of lists
massvolume = [[12,20,32],[36,18,10]]

In [10]:
#Create a 2D NumPy array from a list of list
massvolume_array = np.array(massvolume)

In [11]:
type(massvolume_array)

numpy.ndarray

In [18]:
print(massvolume_array)

[[12 20 32]
 [36 18 10]]


## Seeing the shape of NumPy array 

In [13]:
#See how many rows and columns there are
massvolume_array.shape

(2, 3)

## Subsetting a 2D NumPy array 

In [20]:
#Row "1" = 2 and Column "2" = 3
massvolume_array[1,2]

10

In [17]:
massvolume_array[0]

array([12, 20, 32])

In [23]:
massvolume_array[0:1, 1:3]

array([[20, 32]])